### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by FelixWeichselgartner** [DEMON1A/Network-Scanner#1]
Hi,

how can this have MIT-License, when scapy has GPLv2-License?

Greetings

**Comment by FelixWeichselgartner** [comment]
Maybe this applies: https://www.gnu.org/licenses/gpl-faq.html#WhatIfWorkIsShort ?
Or see: bwaldvogel/neighbourhood#3

**Comment by DEMON1A** [comment]
Thanks for your response here, I didn't actually know about that the project violate scapy GPL license, I will change the license to avoid any issues, and thanks for your time making things clear

Cheers

**Comment by DEMON1A** [comment]
- This issue has been fixed, the PR is merged: #2, Thanks again for your help
